config/routes.rb
Tokimonstracker::Application.routes.draw do
  resources :tokimons  do
    collection do
      get 'display'
    end
  end
  resources :trainers
  root :to => 'tokimons#index'
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/tokimon.rb
class Tokimon < ActiveRecord::Base
  attr_accessible :electric, :fight, :fire, :fly, :frozen_or_ice, :height, :name, :total, :trainer_id, :water, :weight
  belongs_to :trainer
  before_create :check_name_existence
  after_save :update_level
  validates_presence_of :name, :message => "of tokimon is required"
  validates_presence_of :weight, :message => "of tokimon is required"
  validates_presence_of :height, :message => "of tokimon is required"

  def update_level
    c = trainer.tokimons.size
    if c > 3
      trainer.level = c/3
    else
      trainer.level = 1
    end
    trainer.save!
  end

  def check_name_existence
    tokimons = Tokimon.where(:name => self.name)
    if !tokimons.blank?
      errors.add(:base, "Tokimon with same name already exists")
      return false
    end
    return true
  end
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  attr_accessible :email, :level, :name
  has_many :tokimons, dependent: :destroy
  before_save :update_level

  def update_level
    c = tokimons.size
    if c > 3
      self.level = c/3
    else
      self.level = 1
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tokimons_controller.rb
class TokimonsController < ApplicationController
  before_filter :set_tokimon, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tokimons = Tokimon.all
    respond_with(@tokimons)
  end

  def display
    @tokimons = Tokimon.all
    respond_with(@tokimons)
  end

  def show
    respond_with(@tokimon)
  end

  def new
    @tokimon = Tokimon.new
    respond_with(@tokimon)
  end

  def edit
  end

  def create
    @tokimon = Tokimon.new(params[:tokimon])
    @tokimon.save
    respond_with(@tokimon)
  end

  def update
    @tokimon.update_attributes(params[:tokimon])
    respond_with(@tokimon)
  end

  def destroy
    @tokimon.destroy
    respond_with(@tokimon)
  end

  private
    def set_tokimon
      @tokimon = Tokimon.find(params[:id])
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_filter :set_trainer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @trainers = Trainer.all
    respond_with(@trainers)
  end

  def show
    respond_with(@trainer)
  end

  def new
    @trainer = Trainer.new
    respond_with(@trainer)
  end

  def edit
  end

  def create
    @trainer = Trainer.new(params[:trainer])
    @trainer.save
    respond_with(@trainer)
  end

  def update
    @trainer.update_attributes(params[:trainer])
    respond_with(@trainer)
  end

  def destroy
    p @trainer
    @trainer.destroy
    respond_with(@trainer)
  end

  private
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter 
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user) 
    if @user.persisted? 
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated 
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format? 
    else 
      session["devise.twitter_uid"] = request.env["omniauth.auth"] 
      redirect_to new_user_registration_url
    end
  end

  def venmo 
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user) 
    if @user.persisted? 
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated 
      set_flash_message(:notice, :success, :kind => "Venmo") if is_navigational_format? 
    else 
      session["devise.twitter_uid"] = request.env["omniauth.auth"] 
      redirect_to new_user_registration_url
    end
  end  


 # def twitter
 #    @user = User.find_for_oauth(env["omniauth.auth"], current_user)
 #    if @user.persisted?
 #      sign_in_and_redirect @user, :event => :authentication
 #      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
 #    else
 #      session["devise.twitter_uid"] = env["omniauth.auth"]
 #      redirect_to new_user_registration_url
 #    end
 #  end

  # def facebook
  #   @user = User.find_for_oauth(env["omniauth.auth"], current_user)
  #   if @user.persisted?
  #     sign_in_and_redirect @user, :event => :authentication
  #     set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
  #   else
  #     session["devise.facebook_data"] = env["omniauth.auth"]
  #     redirect_to new_user_registration_url
  #   end
  # end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tokimons_helper.rb
module TokimonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseOmniauth</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>


</body>
</html>

app/views/tokimons/_form.html.erb
<%= form_for(@tokimon, html: {class:"form-horizontal"}) do |f| %>
<% if @tokimon.errors.any? %>
<div id="error_explanation" class="<%= 'well' if @tokimon.errors.present? %>">
  <h4><%= pluralize(@tokimon.errors.count, "error") %> prohibited this tokimon from being saved:</h4>

  <ul>
    <% @tokimon.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-sm-6">
    <div class="field">
      <%= f.label :name, class: "control-label"  %><br />
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="field">
      <%= f.label :trainer_id , class: "control-label" %><br />
      <%= f.select :trainer_id, Trainer.all.map{|t| [t.name,t.id] }, {}, {class: 'form-control', style: "color:red;"} %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-3">
    <div class="field">
      <%= f.label :weight, class: "control-label" %><br />
      <%= f.number_field :weight, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :height, class: "control-label" %><br />
      <%= f.number_field :height, class: "form-control"  %>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="field">
      <%= f.label :fly, class: "control-label" %><br />
      <%= f.number_field :fly, class: "form-control ability", min: 0, max: 100  %>
    </div>
    <div class="field">
      <%= f.label :fight, class: "control-label" %><br />
      <%= f.number_field :fight, class: "form-control ability", min: 0, max: 100  %>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="field">
      <%= f.label :fire, class: "control-label" %><br />
      <%= f.number_field :fire, class: "form-control ability", min: 0, max: 100  %>
    </div>
    <div class="field">
      <%= f.label :water, class: "control-label" %><br />
      <%= f.number_field :water, class: "form-control ability", min: 0, max: 100  %>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="field">
      <%= f.label :electric, class: "control-label" %><br />
      <%= f.number_field :electric, class: "form-control ability", min: 0, max: 100  %>
    </div>
    <div class="field">
      <%= f.label :frozen_or_ice, class: "control-label" %><br />
      <%= f.number_field :frozen_or_ice, class: "form-control ability", min: 0, max: 100  %>
    </div>
    <div class="field">
      <%= f.label :total, class: "control-label" %><br />
      <%= f.number_field :total, class: "form-control total_ability", style:"background-color:lightgrey;" %>
    </div>
  </div>
</div>


<div class="actions">
  <%= f.submit class: "btn btn-primary" %>
</div>
<% end %>

<script>
$(document).on("ready",function(){
  $('.ability').on('input',function(e){
    total_abilities();
  });
});

function total_abilities(){
  var sum = 0;
  $('.ability').each(function(){
    v = $(this).val();
    if(v.length == 0 || isNaN(v)) {
      v = 0.0;
      console.log("nan")
    }
    else{
      sum += parseInt(v);
    }
  });
  $(".total_ability").val(sum);
}
</script>

app/views/tokimons/display.html.erb
<div class="row">
  <div class="col-sm-6">
    <h3>Tokimons</h3>
  </div>
  <div class="col-sm-6">
    <%= link_to 'Back', tokimons_path, class:"btn btn-default pull-right", style: "margin-left:10px;margin-top:10px;" %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12" id="container-box" style="overflow:scroll; overflow-y:visible;">

      <% @tokimons.each do |tokimon| %>
        <div class="border text-center" style="display:inline-block;margin:5px;width:<%= tokimon.weight %>px;height:<%= tokimon.height %>px"><%= tokimon.name %></div>
      <% end %>

  </div>
</div>
<style>
#container-box{background:#EEE;padding:5em;white-space:nowrap;vertical-align:bottom;}
#container-box div{border:1px darkblue solid;vertical-align:bottom; display:inline-block;left:0;margin-right:1em; }
.red-bg{background:red;}
.green-bg{background:green;}
.blue-bg{background:blue;}

</style>

app/views/tokimons/edit.html.erb
<h3>Editing <%= @tokimon.name %></h3>

<%= render 'form' %>

<%= link_to 'Show', @tokimon %> |
<%= link_to 'Back', tokimons_path %>

app/views/tokimons/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h3>Tokimons</h3>
  </div>
  <div class="col-sm-6">
    <%= link_to 'Trainers', trainers_path, class:"btn btn-default pull-right", style: "margin-left:10px;margin-top:10px;" %>
    <%= link_to '+ New Tokimon', new_tokimon_path, class:"btn btn-primary pull-right", style: "margin-top:10px;" %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Weight</th>
        <th>Height</th>
        <th>Fly</th>
        <th>Fight</th>
        <th>Fire</th>
        <th>Water</th>
        <th>Electric</th>
        <th>Frozen or ice</th>
        <th>Total</th>
        <th>Trainer</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @tokimons.each do |tokimon| %>
      <tr>
        <td><%= tokimon.name %></td>
        <td><%= tokimon.weight %></td>
        <td><%= tokimon.height %></td>
        <td><%= tokimon.fly %></td>
        <td><%= tokimon.fight %></td>
        <td><%= tokimon.fire %></td>
        <td><%= tokimon.water %></td>
        <td><%= tokimon.electric %></td>
        <td><%= tokimon.frozen_or_ice %></td>
        <td><%= tokimon.total %></td>
        <td><%= tokimon.trainer.name rescue "" %></td>
        <td><%= link_to 'View', tokimon %></td>
        <td><%= link_to 'Edit', edit_tokimon_path(tokimon) %></td>
        <td><%= link_to 'Delete', tokimon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

    <%= link_to 'Display', display_tokimons_path, class:"btn btn-warning pull-right", style: "margin-left:10px;margin-top:10px;" %>

app/views/tokimons/new.html.erb
<h1>New tokimon</h1>

<%= render 'form' %>

<%= link_to 'Back', tokimons_path %>

app/views/tokimons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tokimon.name %>
</p>

<p>
  <b>Weight:</b>
  <%= @tokimon.weight %> pounds
</p>

<p>
  <b>Height:</b>
  <%= @tokimon.height %> cms
</p>

<p>
  <b>Fly:</b>
  <%= @tokimon.fly %>
</p>

<p>
  <b>Fight:</b>
  <%= @tokimon.fight %>
</p>

<p>
  <b>Fire:</b>
  <%= @tokimon.fire %>
</p>

<p>
  <b>Water:</b>
  <%= @tokimon.water %>
</p>

<p>
  <b>Electric:</b>
  <%= @tokimon.electric %>
</p>

<p>
  <b>Frozen or ice:</b>
  <%= @tokimon.frozen_or_ice %>
</p>

<p>
  <b>Total:</b>
  <%= @tokimon.total %>
</p>

<p>
  <b>Trainer:</b>
  <%= @tokimon.trainer.name rescue ""%>
</p>


<%= link_to 'Edit', edit_tokimon_path(@tokimon) %> |
<%= link_to 'Back', tokimons_path %>

app/views/trainers/_form.html.erb
<%= form_for(@trainer) do |f| %>
  <% if @trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% @trainer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing trainer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h3>Trainers</h3>
  </div>
  <div class="col-sm-6">
    <%= link_to 'Tokimons', tokimons_path, class:"btn btn-default pull-right", style: "margin-left:10px;margin-top:10px;" %>
    <%= link_to '+ New Trainer', new_trainer_path, class:"btn btn-warning pull-right", style: "margin-top:10px;" %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Level</th>
        <th>Tokimons</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.name rescue "" %></td>
        <td><%= trainer.email rescue "" %></td>
        <td><%= trainer.level rescue ""%></td>
        <td><%= trainer.tokimons.size rescue ""%></td>
        <td><%= link_to 'View', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Delete', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/trainers/new.html.erb
<h1>New trainer</h1>

<%= render 'form' %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @trainer.name %>
</p>

<p>
  <b>Email:</b>
  <%= @trainer.email %>
</p>

<p>
  <b>Level:</b>
  <%= @trainer.level %>
</p>


<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>